version: '3.9'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./user-management-service/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  user-management:
    build: ./user-management-service
    depends_on:
      - mysql
    networks:
      - backend

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - user-management

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-broker:
    build: ./kafka-broker
    ports:
    
      - "3002:3002"
    environment:
      PORT: 3000
      KAFKA_BROKER: kafka:9092
      KAFKA_CLIENT_ID: kafka-broker-service
    depends_on:
      - kafka
networks:
  backend:
