CREATE DATABASE IF NOT EXISTS statistics;
USE statistics;

CREATE TABLE IF NOT EXISTS statistics (
  courseId VARCHAR(50) PRIMARY KEY,
  count INT DEFAULT 0,
  total FLOAT DEFAULT 0,
  average FLOAT DEFAULT 0,

  q01_total INT DEFAULT 0, q01_avg FLOAT DEFAULT 0,
  q02_total INT DEFAULT 0, q02_avg FLOAT DEFAULT 0,
  q03_total INT DEFAULT 0, q03_avg FLOAT DEFAULT 0,
  q04_total INT DEFAULT 0, q04_avg FLOAT DEFAULT 0,
  q05_total INT DEFAULT 0, q05_avg FLOAT DEFAULT 0,
  q06_total INT DEFAULT 0, q06_avg FLOAT DEFAULT 0,
  q07_total INT DEFAULT 0, q07_avg FLOAT DEFAULT 0,
  q08_total INT DEFAULT 0, q08_avg FLOAT DEFAULT 0,
  q09_total INT DEFAULT 0, q09_avg FLOAT DEFAULT 0,
  q10_total INT DEFAULT 0, q10_avg FLOAT DEFAULT 0
);
