CREATE DATABASE IF NOT EXISTS statistics;

USE statistics;

CREATE TABLE IF NOT EXISTS statistics (
  courseId VARCHAR(50) PRIMARY KEY,
  count INT DEFAULT 0,
  total FLOAT DEFAULT 0,
  average FLOAT DEFAULT 0
);
